#!/bin/sh
# Smoke-tests a qc image on synthetic clips generated by the image's own
# ffmpeg: the environment check, a technical analysis, a sampled VMAF and
# small H.264 and AV1 ladders. Runs as the calling user, as the docs advise
# on Linux, so the reports land in a directory it owns.
#
#   packaging/docker/smoke-test.sh [image]   (default: qc)
set -eu

image=${1:-qc}
work=$(mktemp -d)
trap 'rm -rf "$work"' EXIT

run() {
	docker run --rm --user "$(id -u):$(id -g)" -v "$work:/data" "$image" "$@"
}

ffmpeg() {
	docker run --rm --user "$(id -u):$(id -g)" -v "$work:/data" --entrypoint ffmpeg "$image" \
		-hide_banner -loglevel error -y "$@"
}

step() {
	printf '\n==> %s\n' "$*"
}

step "generate synthetic clips"
ffmpeg -f lavfi -i "testsrc2=size=640x360:rate=25:duration=4,noise=alls=8:allf=t" \
	-c:v libx264 -crf 12 -preset veryfast -pix_fmt yuv420p source.mp4
ffmpeg -i source.mp4 -c:v libx264 -crf 38 -preset veryfast encode.mp4

step "qc version --check"
run version --check

step "qc analyze"
run analyze source.mp4 -o analyze.json > /dev/null
grep -q '"frameCount": 100' "$work/analyze.json"

step "qc vmaf --sample 5%"
run vmaf source.mp4 encode.mp4 --sample 5% -f json > "$work/vmaf.json"
grep -q '"model"' "$work/vmaf.json"

for codec in h264 av1; do
	step "qc ladder -c $codec"
	run ladder source.mp4 -c "$codec" --heights 360,180 --max-rungs 2 -o "ladder-$codec.json" --html "ladder-$codec.html" > /dev/null
	grep -q '"rungs"' "$work/ladder-$codec.json"
	test -s "$work/ladder-$codec.html"
done

printf '\nsmoke tests passed: %s\n' "$image"
